default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: raving_recipes_development


test:
  <<: *default
  database: raving_recipes_test


production:
  <<: *default
  database: raving_recipes_production
  username: raving_recipes
  password: <%= ENV['RAVING_RECIPES_DATABASE_PASSWORD'] %>
